# Generated by Django 6.0.2 on 2026-02-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaasApp', '0003_projects_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('MANAGER', 'manager'), ('MEMBER', 'member')], default='MEMBER', max_length=20),
        ),
    ]
